/**
 * 采光分析 - 全局配置
 * 迁移自 building-sunlight-simulator/js/config.js，去除 i18n 相关内容，仅保留中文场景所需常量
 */

export const SUNLIGHT_CONFIG = {
  DEFAULTS: {
    LATITUDE: 36.65,
    LONGITUDE: 117.12,
    TIME_ZONE: 'Asia/Shanghai',
    CITY: '济南',
    NORTH_ANGLE: 0,
    FLOORS: 18,
    FLOOR_HEIGHT: 3,
    UNITS_PER_FLOOR: 2,
    IS_THIS_COMMUNITY: true,
    SCALE_DISTANCE: 50,
    TIME_HOUR: 10,
    SEASON: -23.44,
  },

  SOLAR_DECLINATION: {
    WINTER_SOLSTICE: -23.44,
    EQUINOX: 0,
    SUMMER_SOLSTICE: 23.44,
  },

  SOLAR_TERMS_DATES: {
    WINTER_SOLSTICE: '12-22',
    SPRING_EQUINOX: '03-20',
    AUTUMN_EQUINOX: '09-23',
    SUMMER_SOLSTICE: '06-21',
  },

  TIME: {
    MIN_HOUR: 6,
    MAX_HOUR: 18,
    STEP: 0.05,
  },

  SUNLIGHT_ANALYSIS: {
    TIME_INTERVAL: 0.1,
    WINDOW_HEIGHT_OFFSET: 1.2,
    FLOOR_HEIGHT_RATIO: 0.4,
    MAX_HOURS: 8,
    REFERENCE_HOURS: 2,
    MAX_SAMPLE_POINTS: 20000,
    MAX_RAY_STEPS: 2400000,
    MAX_OCCLUSION_WORK: 50000000,
    REFERENCE_TRIANGLES_PER_MESH: 12,
    MAIN_THREAD_BATCH_SIZE: 240,
    PRECOMPUTED_SCHEMA_VERSION: 1,
    PRECOMPUTED_ALGORITHM_VERSION: '3.2.0-1',
    MAX_PRECOMPUTED_ENTRIES: 24,
  },

  SCENE: {
    BACKGROUND_COLOR: 0xd8e8f5,
    FOG_COLOR: 0xd8e8f5,
    FOG_NEAR: 120,
    FOG_FAR: 1500,
    CAMERA_FOV: 45,
    CAMERA_NEAR: 1,
    CAMERA_FAR: 5000,
    CAMERA_POSITION: { x: 200, y: 260, z: 320 },
  },

  LIGHTING: {
    SUN_INTENSITY: 0.9,
    AMBIENT_INTENSITY: 0.42,
    AMBIENT_COLOR: 0x9fb3c8,
    SHADOW_MAP_SIZE: 4096,
    SHADOW_BIAS: -0.0001,
    MIN_SUN_INTENSITY: 0.75,
    MAX_SUN_INTENSITY: 0.85,
    MIN_AMBIENT_INTENSITY: 0.35,
    MAX_AMBIENT_INTENSITY: 0.45,
  },

  MATERIALS: {
    GROUND_COLOR: 0xc8ddf0,
    ROOF_COLOR: 0xe8eaed,
    BUILDING_COLOR: 0x9fb0c4,
    BUILDING_ROUGHNESS: 0.6,
    NEIGHBOR_COLOR: 0xb7c2cf,
    NEIGHBOR_OPACITY: 0.92,
  },

  EDITOR: {
    CLOSE_EPSILON: 8,
    SANITIZE_EPSILON: 0.75,
    MIN_POLYGON_POINTS: 3,
    ZOOM_SPEED: 0.1,
    MIN_ZOOM: 0.1,
    MAX_ZOOM: 10,
    CANVAS_PADDING: 40,
  },

  VALIDATION: {
    LATITUDE: { MIN: -90, MAX: 90 },
    LONGITUDE: { MIN: -180, MAX: 180 },
    NORTH_ANGLE: { MIN: -180, MAX: 180 },
    FLOORS: { MIN: 1, MAX: 300 },
    FLOOR_HEIGHT: { MIN: 1, MAX: 20 },
    UNITS: { MIN: 1, MAX: 50 },
    BUILDINGS: { MIN: 1, MAX: 500 },
    POLYGON_POINTS: { MIN: 3, MAX: 200 },
    MIN_POLYGON_AREA: 0.0001,
  },
};
